# -*- coding: utf-8 -*-
"""Reto 12

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MeEUErh9BnTVlDq7LtoTVwB8r40oxgjn
"""

from collections import Counter

def VocalesYConsonantes(doc_ok):
    c_vocales = 0
    c_consonantes = 0

    for letra in doc_ok:                                                       # Va mirando cada letra del archivo
      letra_min=letra.lower()                                                  # Para convertirlas todas a minuscula y hacer solo un condicional
      if letra_min in "aeiouáéíóú":                                            # Busca si es vocal
        c_vocales += 1
      elif letra_min in "bcdfghjklmnñpqrstvwxyz":                              # Busca si es consonante
        c_consonantes += 1

    print("El número de vocales es: " +str(c_vocales))
    print("El número de consonantes es: " +str(c_consonantes))

def PalabrasMasRepetidas(doc_ok):
    doc_ok = doc_ok.split()                                                    # Para seprar las palabras
    p_repetidas = Counter(doc_ok).most_common(50)                              # Las que más aparecen se añaden a la variable con el top 50
    print("Las 50 palabras que más se repiten son: " + str(p_repetidas))

if __name__ == "__main__":
  with open("mbox-short.txt", "r") as doc:                                     # Para importar el archivo
    doc_ok = doc.read()                                                        # Lee el archivo
  VocalesYConsonantes(doc_ok)                                                  # Se llama la función para hallar número de vocales y consonantes
  PalabrasMasRepetidas(doc_ok)                                                 # Se llama la función para hallar las 50 palabras más repetidas